# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-06T15:07:06+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional, Union

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class FixedLocation(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    uprn: Optional[str] = None
    sao_text: Optional[str] = Field(None, alias='saoText')
    pao_text: Optional[str] = Field(None, alias='paoText')
    street_description: Optional[str] = Field(None, alias='streetDescription')
    locality: Optional[str] = None
    town_name: Optional[str] = Field(None, alias='townName')
    post_town: Optional[str] = Field(None, alias='postTown')
    postcode: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None
    formatted_address: Optional[str] = Field(None, alias='formattedAddress')
    full_address_search: Optional[str] = Field(None, alias='fullAddressSearch')


class OverseasLocation(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    country_name: str = Field(..., alias='countryName')
    country_code: str = Field(..., alias='countryCode')
    location_display: Optional[str] = Field(None, alias='locationDisplay')


class Salary(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    minimum: float
    maximum: Optional[float] = None
    currency: str
    currency_symbol: Optional[str] = Field(None, alias='currencySymbol')
    salary_details: Optional[str] = Field(None, alias='salaryDetails')


class Contacts(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    contact_name: Optional[str] = Field(None, alias='contactName')
    contact_email: Optional[EmailStr] = Field(None, alias='contactEmail')
    contact_phone: Optional[str] = Field(None, alias='contactPhone')


class Approach(Enum):
    internal = 'Internal'
    across_government = 'Across Government'
    external = 'External'


class Assignments(Enum):
    apprentice = 'Apprentice'
    fixed_term_appointment__fta_ = 'Fixed Term Appointment (FTA)'
    loan = 'Loan'
    secondment = 'Secondment'
    permanent = 'Permanent'


class Grade(Enum):
    senior_civil_service___permanent_secretary = (
        'Senior Civil Service - Permanent Secretary'
    )
    senior_civil_service___director_general__pb3_ = (
        'Senior Civil Service - Director General (PB3)'
    )
    senior_civil_service___director__pb2_ = 'Senior Civil Service - Director (PB2)'
    senior_civil_service___deputy_director__pb1_1_a_ = (
        'Senior Civil Service - Deputy Director (PB1/1A)'
    )
    grade_6_equivalent = 'Grade 6 Equivalent'
    grade_7_equivalent = 'Grade 7 Equivalent'
    senior_executive_officer__seo__equivalent = (
        'Senior Executive Officer (SEO) Equivalent'
    )
    higher_executive_officer__heo__equivalent = (
        'Higher Executive Officer (HEO) Equivalent'
    )
    executive_officer__eo__equivalent = 'Executive Officer (EO) Equivalent'
    administrative_officer__ao__equivalent = 'Administrative Officer (AO) Equivalent'
    administrative_assistant__aa__equivalent = (
        'Administrative Assistant (AA) Equivalent'
    )


class Profession(Enum):
    actuary = 'Actuary'
    commercial = 'Commercial'
    communications = 'Communications'
    corporate_finance = 'Corporate Finance'
    counter_fraud = 'Counter Fraud'
    digital_and_data = 'Digital and Data'
    economics = 'Economics'
    finance = 'Finance'
    geography = 'Geography'
    human_resources = 'Human Resources'
    intelligence_analysis = 'Intelligence Analysis'
    internal_audit = 'Internal Audit'
    international_trade = 'International Trade'
    knowledge_and_information_management = 'Knowledge and Information Management'
    legal = 'Legal'
    clinical = 'Clinical'
    occupational_psychology = 'Occupational Psychology'
    operational_delivery = 'Operational Delivery'
    operational_research = 'Operational Research'
    planning = 'Planning'
    planning_inspection = 'Planning Inspection'
    policy = 'Policy'
    project_delivery = 'Project Delivery'
    property = 'Property'
    risk_management = 'Risk Management'
    science_and_engineering = 'Science and Engineering'
    security = 'Security'
    social_research = 'Social Research'
    statistics = 'Statistics'
    tax = 'Tax'
    veterinary = 'Veterinary'


class Error(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    code: Optional[int] = None
    message: Optional[str] = None


class Job(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: Optional[str] = Field(
        None,
        description='Internal unique identifier (may be present in source systems)',
    )
    external_id: str = Field(
        ...,
        alias='externalId',
        description='External canonical identifier for the job (required)',
    )
    approach: Approach
    title: str
    description: str
    organisation: str
    location: Union[list[FixedLocation], list[OverseasLocation]] = Field(
        ..., description='Array of fixed locations OR array of overseas locations'
    )
    grade: Union[Grade, str]
    assignment_type: Assignments = Field(..., alias='assignmentType')
    personal_spec: str = Field(..., alias='personalSpec')
    apply_detail: str = Field(..., alias='applyDetail')
    closing_date: AwareDatetime = Field(..., alias='closingDate')
    profession: Profession
    recruitment_email: EmailStr = Field(..., alias='recruitmentEmail')
    contacts: Optional[list[Contacts]] = None
    nationality_requirement: Optional[str] = Field(None, alias='nationalityRequirement')
    summary: Optional[str] = None
    apply_url: Optional[AnyUrl] = Field(None, alias='applyUrl')
    benefits: Optional[str] = None
    salary: Optional[Salary] = None


class JobResultItem(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    id: str = Field(..., description='Internal unique identifier')
    external_id: str = Field(
        ...,
        alias='externalId',
        description='External identifier (e.g. originating system id). Used as canonical identifier.',
    )
    title: str
    organisation: str
    location: Union[list[FixedLocation], list[OverseasLocation]] = Field(
        ..., description='Array of fixed locations OR array of overseas locations'
    )
    assignment_type: Optional[Assignments] = Field(None, alias='assignmentType')
    salary: Optional[Salary] = None
    closing_date: Optional[AwareDatetime] = Field(None, alias='closingDate')
    profession: Optional[Profession] = None
    approach: Optional[Approach] = None


class JobSearchResponse(BaseModel):
    model_config = ConfigDict(
        frozen=True,
    )
    results: list[JobResultItem]
    total: int
    page: int
    page_size: int = Field(..., alias='pageSize')
    total_pages: int = Field(..., alias='totalPages')
    query: Optional[str] = None
    applied_filters: Optional[str] = Field(None, alias='appliedFilters')
