#!/usr/bin/env bash
# Generate Pydantic models from OpenAPI schemas

set -e

echo "Generating Pydantic models from OpenAPI schemas..."

# Check if datamodel-code-generator is installed
if ! command -v datamodel-codegen &> /dev/null; then
    echo "datamodel-code-generator not found. Installing..."
    pip install "datamodel-code-generator[http]>=0.25.0"
fi

# Generate models for Jobs API - only if it has schemas defined
if grep -q "schemas:" schemas/jobs/openapi.yaml && grep -A 1 "schemas:" schemas/jobs/openapi.yaml | grep -v "schemas: {}" | grep -qv "^--$"; then
    echo "Generating Jobs API models..."
    datamodel-codegen \
        --input schemas/jobs/openapi.yaml \
        --input-file-type openapi \
        --output generated/python/jobs/models.py \
        --output-model-type pydantic_v2.BaseModel \
        --use-standard-collections \
        --use-schema-description \
        --field-constraints \
        --snake-case-field \
        --use-default \
        --enable-faux-immutability
else
    echo "Jobs API schema is empty, creating placeholder..."
    mkdir -p generated/python/jobs
    cat > generated/python/jobs/models.py << 'MODELS_EOF'
# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-12-06T15:00:00+00:00

from __future__ import annotations

"""
Jobs API Models

This schema is currently empty. Models will be generated when the Jobs API schema is defined.
"""

__all__: list[str] = []
MODELS_EOF
fi

# Generate models for Search API
echo "Generating Search API models..."
datamodel-codegen \
    --input schemas/search/openapi.yaml \
    --input-file-type openapi \
    --output generated/python/search/models.py \
    --output-model-type pydantic_v2.BaseModel \
    --use-standard-collections \
    --use-schema-description \
    --field-constraints \
    --snake-case-field \
    --use-default \
    --enable-faux-immutability

echo "✓ Pydantic models generated successfully!"
